version: 0.0
os: linux
files:
  - source: /
    destination: /home/runner/work/ec2-project/ec2-project
permissions:
  - object: /home/runner/work/ec2-project/ec2-project
    owner: ubuntu
    group: ubuntu
